name: test
on: [push]
jobs:
  'prove-lrt':
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.24', '5.26', '5.28', '5.30', '5.32', '5.34']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{matrix.perl}}
      - run: lsb_release -a
      - run: sudo apt-get install libtirpc-dev pkg-config
      - run: perl Makefile.PL
      - run: make
      - run: cpanm Test::Pod
      - run: prove --blib --verbose --recurse t/
      
      
